# 🧑‍💻 NumPy Complete Guided Project
**Instructor / Student Colab Notebook** – covers *all* key concepts from `Numpy‑1` to `Numpy‑5`.

*Generated: 08 Aug 2025*


**Table of Contents**

1. [Setup](#setup)  
2. [Array Creation & Dtypes](#creation)  
3. [Array Attributes & Inspection](#attributes)  
4. [Indexing, Slicing, Fancy Indexing](#indexing)  
5. [Reshaping, Transpose & Copies vs Views](#reshape)  
6. [Joining, Splitting, Set & Sorting Ops](#join)  
7. [Arithmetic Ops, Universal Functions](#arithmetic)  
8. [Broadcasting (Rules + Examples)](#broadcast)  
9. [Statistics & Aggregations](#stats)  
10. [Random Numbers & Reproducibility](#random)  
11. [Structured / Recarrays](#structured)  
12. [Linear Algebra Essentials](#linalg)  
13. [File I/O (`npy`, `npz`, `txt`)](#io)  
14. [Datetime64 & Timedelta64](#datetime)  
15. [Masked Arrays & NaNs](#mask)  
16. [Mini‑Project — Fitness Data Analysis](#project)  
17. [Conclusion & Next Steps](#conclusion)  


## <a name='setup'></a>1️⃣ Setup

In [ ]:
import numpy as np, math, os, pathlib, types, textwrap, random
print('NumPy version:', np.__version__)

## <a name='creation'></a>2️⃣ Array Creation & Dtypes

Key functions: `np.array`, `np.arange`, `np.linspace`, `zeros`, `ones`, `full`, `eye`, `identity`, `diag`, `empty`

In [ ]:
# EXAMPLE
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.linspace(0, 1, 6)
arr3 = np.full((2,3), 7.5)
print(arr1, arr2, arr3, sep="\n")
print("dtypes:", arr1.dtype, arr2.dtype)


In [4]:
# 🖊️ TODO: create a 10×10 chessboard pattern using zeros & ones
import numpy as np, math, os, pathlib, types, textwrap, random
chessboard = np.full((10, 10), 0)

chessboard[1::2, ::2]=1
chessboard[::2, 1::2]= 1

print(chessboard)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


## <a name='attributes'></a>3️⃣ Array Attributes & Inspection

`shape`, `ndim`, `size`, `dtype`, `itemsize`, `nbytes`

In [ ]:
M = np.arange(12).reshape(3,4)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


In [9]:
# 🖊️ TODO: check memory footprint of a 1000×1000 float64 array
import numpy as np, math, os, pathlib, types, textwrap, random
array = np.zeros((1000, 1000), dtype=np.float64)
print("shape: ",array.shape)
print("dim", array.ndim)
print("size: ", array.size)
print("itemsize", array.itemsize)
print("bytes: ", array.nbytes)
print("data type: ", array.dtype)



shape:  (1000, 1000)
dim 2
size:  1000000
itemsize 8
bytes:  8000000
data type:  float64


## <a name='indexing'></a>4️⃣ Indexing, Slicing & Fancy Indexing

In [ ]:
a = np.arange(1,26).reshape(5,5)
print(a[:, 0])     # first column
print(a[::2, ::2]) # every 2nd row/col
mask = (a % 3 == 0)
print('multiples of 3:', a[mask])


In [10]:
# 🖊️ TODO: use fancy indexing to swap first and last rows of `a`
import numpy as np

a = np.arange(1, 13).reshape(4, 3)
a[[0, -1]] = a[[-1, 0]]

print("\nAfter swapping first and last rows:\n", a)



After swapping first and last rows:
 [[10 11 12]
 [ 4  5  6]
 [ 7  8  9]
 [ 1  2  3]]


## <a name='reshape'></a>5️⃣ Reshaping, Transpose & Copies vs Views

In [ ]:
b = np.arange(8)
B = b.reshape(2,4)
B[0,0] = 99
print('b is modified:', b)
C = b.reshape(2,4).copy()
C[0,0] = -1
print('b unchanged with copy:', b)


In [ ]:
# 🖊️ TODO: Flatten a 3‑D array into 1‑D using both `ravel` and `flatten`; observe copy vs view.


## <a name='join'></a>6️⃣ Joining, Splitting, Set & Sorting Ops

In [ ]:
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print('union', np.union1d(x,y))
print('intersect', np.intersect1d(xy,[1,2,10]))
print('sorted descending', np.sort(xy)[::-1])


In [ ]:
# 🖊️ TODO: split `xy` back into two equal halves using `np.array_split`


## <a name='arithmetic'></a>7️⃣ Arithmetic Ops & Universal Functions

In [ ]:
v = np.arange(5)
print('exp', np.exp(v))
print('sin', np.sin(v))
print('vectorised addition', v + 10)


In [ ]:
# 🖊️ TODO: given degrees [0,30,45,60,90], compute radians and sin values.


## <a name='broadcast'></a>8️⃣ Broadcasting Rules

Rules: compare dimensions from right → left; stretch size 1 dims; mismatch error.

In [ ]:
row = np.arange(5)
col = np.arange(3).reshape(3,1)
matrix = row + col  # broadcast to 3×5
print(matrix)


In [ ]:
# 🖊️ TODO: use broadcasting to create a 10×10 multiplication table.


## <a name='stats'></a>9️⃣ Statistics & Aggregations

In [ ]:
data = np.random.default_rng(0).integers(1, 100, size=(5,4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))


In [ ]:
# 🖊️ TODO: compute `np.percentile` (25th, 50th, 75th) of flattened `data`.


## <a name='random'></a>🔟 Random Numbers & Reproducibility

In [ ]:
rng = np.random.default_rng(42)
rand_floats = rng.random(5)
rand_ints = rng.integers(low=10, high=50, size=5)
print(rand_floats, rand_ints)
rng2 = np.random.default_rng(42)
assert np.allclose(rand_floats, rng2.random(5))


In [ ]:
# 🖊️ TODO: simulate rolling a fair six‑sided die 100 times; estimate proportion of 6s.


## <a name='structured'></a>1️⃣1️⃣ Structured / Record Arrays

In [ ]:
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                   dtype=[('name','U10'), ('age','i4'), ('weight','f4')])
print(people['name'], people['age'].mean())


In [ ]:
# 🖊️ TODO: add a new field 'height' to the structured array using `np.lib.recfunctions.append_fields` (hint: pip install?).


## <a name='linalg'></a>1️⃣2️⃣ Linear Algebra Essentials

In [ ]:
A = np.random.random((3,3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))


In [ ]:
# 🖊️ TODO: compute eigenvalues of `A` using `np.linalg.eig`.


## <a name='io'></a>1️⃣3️⃣ File I/O (`npy`, `npz`, `txt`)

In [ ]:
np.save('array.npy', A)
loaded = np.load('array.npy')
print('loaded equals A?', np.allclose(loaded, A))
np.savez('multi_arrays.npz', A=A, b=b)


In [ ]:
# 🖊️ TODO: Use `np.savetxt` to write `data` (from stats section) to CSV then reload with `np.loadtxt`.


## <a name='datetime'></a>1️⃣4️⃣ Datetime64 & Timedelta64

In [ ]:
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])


In [ ]:
# 🖊️ TODO: find how many Mondays appear in `dates` array.


## <a name='mask'></a>1️⃣5️⃣ Masked Arrays & NaNs

In [ ]:
arr = np.array([1, 2, np.nan, 4, np.nan])
masked = np.ma.masked_invalid(arr)
print(masked.mean())


In [ ]:
# 🖊️ TODO: replace NaNs with column means in a 2‑D array containing NaNs.


## <a name='project'></a>1️⃣6️⃣ Mini‑Project: Fitness Data Analysis

Load `fitness.txt` (tab‑separated) then follow prompts.

In [ ]:
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))


In [ ]:
# 🖊️ TODO: Monthly step count, sleep vs mood correlation, weekly summary, etc.


## <a name='conclusion'></a>1️⃣7️⃣ Conclusion & Further Practice
Congrats on covering **all core NumPy topics** from your five lecture notebooks!

*Keep experimenting, read the official docs, and try converting your NumPy pipelines into Pandas or JAX for more fun.*